# Generated by Django 3.2.8 on 2021-10-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос')),
                ('option_a', models.CharField(max_length=250, verbose_name='Выбор A')),
                ('option_b', models.CharField(max_length=250, verbose_name='Выбор B')),
                ('option_c', models.CharField(max_length=250, verbose_name='Выбор C')),
                ('option_d', models.CharField(max_length=250, verbose_name='Выбор D')),
                ('correct_answer', models.CharField(choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=5, verbose_name='Правильный ответ')),
            ],
        ),
    ]
